// <auto-generated />
namespace MVS.LAB._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Edjjkj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edjjkj));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060121446_Edjjkj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
